const products = [
  // --- CLOTHING ---
  {
    id: 1,
    name: '"This Is Fine" Dog Tee',
    category: 'clothing',
    price: 24.99,
    emoji: '🐶🔥',
    tag: 'bestseller',
    desc: 'Everything is fine. Soft 100% cotton unisex tee.',
    sizes: ['S','M','L','XL','2XL'],
  },
  {
    id: 2,
    name: 'Distracted Boyfriend Hoodie',
    category: 'clothing',
    price: 49.99,
    emoji: '👀',
    tag: 'hot',
    desc: 'Classic meme energy. Heavyweight pullover hoodie.',
    sizes: ['S','M','L','XL','2XL'],
  },
  {
    id: 3,
    name: 'Doge "Much Wow" Tee',
    category: 'clothing',
    price: 22.99,
    emoji: '🐕',
    tag: null,
    desc: 'Such shirt. Very comfortable. Wow.',
    sizes: ['S','M','L','XL'],
  },
  {
    id: 4,
    name: 'Stonks Man Crewneck',
    category: 'clothing',
    price: 44.99,
    emoji: '📈',
    tag: 'new',
    desc: 'Only go up. Premium fleece crewneck sweatshirt.',
    sizes: ['S','M','L','XL','2XL'],
  },
  {
    id: 5,
    name: 'Drake Approves Hoodie',
    category: 'clothing',
    price: 49.99,
    emoji: '🙅✅',
    tag: null,
    desc: 'No vs. Yes. A look for every decision in life.',
    sizes: ['S','M','L','XL'],
  },
  {
    id: 6,
    name: 'NPC Main Character Tee',
    category: 'clothing',
    price: 26.99,
    emoji: '🎮',
    tag: 'new',
    desc: 'Are you the main character or just an NPC? You decide.',
    sizes: ['S','M','L','XL','2XL'],
  },
  {
    id: 7,
    name: '"Touch Grass" Crop Tee',
    category: 'clothing',
    price: 23.99,
    emoji: '🌿',
    tag: null,
    desc: 'A friendly reminder. Cropped fit, super soft.',
    sizes: ['XS','S','M','L','XL'],
  },
  {
    id: 8,
    name: 'Sigma Grindset Hoodie',
    category: 'clothing',
    price: 52.99,
    emoji: '😤',
    tag: 'hot',
    desc: 'No distractions. No excuses. All grind. Heavyweight zip hoodie.',
    sizes: ['S','M','L','XL','2XL'],
  },

  // --- ACCESSORIES ---
  {
    id: 9,
    name: 'Meme Lord Snapback',
    category: 'accessories',
    price: 29.99,
    emoji: '🧢',
    tag: 'bestseller',
    desc: 'Embroidered logo snapback. One size fits most.',
    sizes: ['One Size'],
  },
  {
    id: 10,
    name: 'Among Us Crewmate Tote',
    category: 'accessories',
    price: 18.99,
    emoji: '🚀',
    tag: null,
    desc: 'sus bag. Heavy-duty canvas tote, 15L capacity.',
    sizes: ['One Size'],
  },
  {
    id: 11,
    name: 'Gigachad Enamel Pin',
    category: 'accessories',
    price: 9.99,
    emoji: '💪',
    tag: 'new',
    desc: 'Hard enamel pin. Gold plated backing. 1.5 inches.',
    sizes: ['One Size'],
  },
  {
    id: 12,
    name: 'Skull Emoji Beanie',
    category: 'accessories',
    price: 24.99,
    emoji: '💀',
    tag: null,
    desc: 'I am literally dead. Ribbed knit winter beanie.',
    sizes: ['One Size'],
  },

  // --- HOME & DECOR ---
  {
    id: 13,
    name: '"Press F" Coffee Mug',
    category: 'home',
    price: 16.99,
    emoji: '☕',
    tag: 'bestseller',
    desc: 'Press F to pay respects. 11oz ceramic mug, dishwasher safe.',
    sizes: ['11oz', '15oz'],
  },
  {
    id: 14,
    name: 'Stonks Wall Poster',
    category: 'home',
    price: 14.99,
    emoji: '🖼️',
    tag: null,
    desc: 'Motivational. Kind of. 18"×24" premium matte print.',
    sizes: ['18x24'],
  },
  {
    id: 15,
    name: 'This Is Fine Desk Mat',
    category: 'home',
    price: 34.99,
    emoji: '🖥️🔥',
    tag: 'new',
    desc: 'Keep your workspace calm(ish). 35"×15" XXL desk mat.',
    sizes: ['35x15'],
  },
  {
    id: 16,
    name: 'Doge Throw Pillow',
    category: 'home',
    price: 27.99,
    emoji: '🐕🛋️',
    tag: null,
    desc: 'Such comfort. Very cozy. 18"×18" pillow with insert.',
    sizes: ['18x18'],
  },

  // --- STICKERS & ART ---
  {
    id: 17,
    name: 'Meme Pack Vol. 1 (10 stickers)',
    category: 'stickers',
    price: 8.99,
    emoji: '🎨',
    tag: 'bestseller',
    desc: '10 premium vinyl stickers. Weatherproof & waterproof.',
    sizes: ['One Size'],
  },
  {
    id: 18,
    name: 'Pepe Sticker Pack (5 stickers)',
    category: 'stickers',
    price: 6.99,
    emoji: '🐸',
    tag: null,
    desc: 'The classics. 5 holographic vinyl Pepe stickers.',
    sizes: ['One Size'],
  },
  {
    id: 19,
    name: 'Rage Comic Print Set',
    category: 'stickers',
    price: 12.99,
    emoji: '😤',
    tag: null,
    desc: 'A trip down memory lane. 4"×4" mini art prints, set of 6.',
    sizes: ['One Size'],
  },
  {
    id: 20,
    name: 'Internet Famous Sticker Sheet',
    category: 'stickers',
    price: 10.99,
    emoji: '⭐',
    tag: 'new',
    desc: '30+ mini stickers on one mega sheet. Pure chaos.',
    sizes: ['One Size'],
  },
];
